name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Download build artifacts'
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

    #   - name: "Setup pnpm"
    #     uses: pnpm/action-setup@v2
    #     with:
    #       version: 8

    #   - name: "Setup Node.js"
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: 18
    #       cache: "pnpm"

    #   # TODO is `--compatibility-date` required calling wrangler?
    #   - name: "Deploy to Cloudflare Pages - ${{ inputs.environment }}"
    #     run: wrangler pages deploy "dist" --project-name "poc-web-application" --branch
    #     env:
    #       CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #       CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # Will also work ???? How can I pass environement???
      - name: 'Publish to Cloudflare Pages'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'poc-web-application'
          directory: 'dist'
          wranglerVersion: '3'
